# Reload config
bind r source-file ~/.config/tmux/tmux.conf

set -g mouse on
# 1. Use Ctrl + y/u to switch Panes (No prefix needed)
bind -n C-y select-pane -L
bind -n C-u select-pane -R

# 2. Use Ctrl + t to create a New Window
bind -n C-t new-window -c "#{pane_current_path}"

# 3. Use Ctrl + k for a Vertical Split
bind -n C-k split-window -h -c "#{pane_current_path}"

# 4. Window Navigation
# Ctrl + Space to cycle windows
bind -n C-Space next-window

# Killing
bind -n C-x kill-pane
# Bind Ctrl + b then d to kill window (standard tmux style but for window)
bind d kill-window
bind -n C-q kill-window

# --- Minimalist Floating Status Bar ---

# 1. Background Transparency
set -g status-style "bg=default"

# 2. Window List (Left Side)
set -g window-status-format "#[fg=white,bg=default] #I:#W "
set -g window-status-current-format "#[fg=cyan,bg=default,bold] #I:#W "
set -g status-justify left

# 4. Clean up the left side
set -g status-left ""

set -g window-status-current-format " #W "
set -g window-status-format " #W "

set -g pane-border-lines simple
set -g pane-border-style fg=black,bright
set -g pane-active-border-style fg=white,bright

# --- Plugins ---
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'

