# Reload config
bind -n C-S-f source-file ~/.config/tmux/tmux.conf

set -g mouse on

is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"

# Bind Ctrl+h/j/k/l to navigation
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'

bind -n C-S-h swap-pane -s '{left-of}'
bind -n C-S-l swap-pane -s '{right-of}'
bind -n C-S-k swap-pane -s '{up-of}'
bind -n C-S-j swap-pane -s '{down-of}'


bind -n C-y command-prompt -p "Cheat:" "display-popup -E -w 80% -h 80% 'curl -s cheat.sh/%% | less -R'"
bind -n C-p command-prompt -p "CppMan:" "display-popup -E -w 80% -h 80% 'cppman %%'"

bind -n C-t new-window -c "#{pane_current_path}"
set -g message-style "bg=default,fg=white"
set -g message-command-style "bg=default,fg=white"

bind -n C-u split-window -v -c "#{pane_current_path}"
bind -n C-o split-window -h -c "#{pane_current_path}"

bind -n C-Space next-window
bind -n C-a previous-window

bind -n C-x kill-pane
bind -n C-q kill-window


set -g status-style "bg=default,fg=colour245"
set -g status-justify centre 
set -g status-left ""
set -g status-right "" # Keeps it super clean; add back %H:%M if you want time

set -g window-status-format "#[fg=colour240,bg=default] #W "

set -g window-status-current-format "#[fg=black,bg=white,bold] #W "

set -g pane-border-lines simple
set -g pane-border-style fg=black,bright
set -g pane-active-border-style fg=white,bright

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'

