# -*- conf -*-

[main]
font=CaskaydiaMono Nerd Font:size=12

[cursor]
style=block
blink=no

[mouse]
hide-when-typing=yes

[colors]
alpha=0.8
background=000000
foreground=bebebe

# Fixed Cursor colors (moved from [cursor] to [colors])
cursor=121212 eaeaea

# Fixed Selection colors (removed selection-target)

## Normal colors

[key-bindings]
fullscreen=F11
