[colors]
background = #00000000
background-alt = #44ffffff
foreground = #ffffff
primary = #ffffff
disabled = #707880

[bar/macos]
# Floating layout
width = 98%
height = 24pt
radius = 12
offset-x = 1%
offset-y = 8pt
fixed-center = true

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 2pt
# Adjusted padding to move the date closer to the edge of the bar
padding-left = 2
padding-right = 2
module-margin = 1

# Font setup
font-0 = "Inter:size=11;2"
font-1 = "Symbols Nerd Font:size=12;3"
font-2 = "JetBrainsMono Nerd Font:style=Bold:size=12;3"

# Modules
modules-left = arch-logo xworkspaces
modules-center = 
modules-right = cpu memory filesystem wlan battery date

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true
wm-restack = i3

# System Tray (for app icons like Discord/NetworkManager)
tray-position = right
tray-padding = 2
tray-background = ${colors.background}

[module/arch-logo]
type = custom/text
content = " 󰣇 "
content-font = 2
content-foreground = ${colors.primary}

[module/xworkspaces]
type = internal/xworkspaces
label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.primary}
label-active-padding = 1
label-occupied = %name%
label-occupied-padding = 1
label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/filesystem]
type = internal/fs
interval = 25
mount-0 = /
label-mounted = " 󰋊 %percentage_used%% "

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "  "
label = "%percentage%% "

[module/memory]
type = internal/memory
interval = 2
format-prefix = "  "
label = "%percentage_used%% "

[module/wlan]
type = internal/network
# Check 'ip link' and change if yours isn't wlan0
interface = wlan0
interface-type = wireless
label-connected = "  %essid% "
label-disconnected = " 󰖪 "

[module/battery]
type = internal/battery
full-at = 99
low-at = 10
# Check 'ls /sys/class/power_supply/' and change if not BAT0
battery = BAT0
adapter = ADP1
poll-interval = 5
format-charging = <label-charging>
format-discharging = <label-discharging>
label-charging = " 󱐥 %percentage%% "
label-discharging = "  %percentage%% "
label-full = "  100% "

[module/date]
type = internal/date
interval = 1
# Clean date format
date = %h %d %H:%M
label = " %date% "
label-foreground = ${colors.primary}

[settings]
screenchange-reload = true
pseudo-transparency = true
