# In hyprland.conf

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

source = ~/.config/hypr/conf/monitors.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/my_keybinds.conf
source = ~/.config/hypr/conf/looknfeel.conf
source = ~/.config/hypr/conf/nvidia.conf
source = ~/.config/hypr/conf/env.conf

exec-once = ~/.config/hypr/scripts/autostart.sh
# Start the swww daemon
exec-once = swww-daemon
# Set the wallpaper on startup
exec-once = swww img /home/ben/.config/hypr/wallpaper/foggywoodlands.jpg > /dev/null 2>&1
exec-once = $HOME/.config/hypr/scripts/waybar_auto_hide &
device {
    name = asus-keyboard
    enabled = true
}

device {
    name = asus-keyboard-2
    enabled = true
}

# -----------------------------------------------------
# Monitor Setup
# -----------------------------------------------------
# Laptop screen (Primary/Left)
monitor = eDP-1, preferred, auto, 1.33
# External monitor (Right)
monitor = HDMI-A-1, preferred, auto, 1

# -----------------------------------------------------
# Workspace Rules
# -----------------------------------------------------
# Bind workspaces 1-5 to the laptop
workspace = 1, monitor:eDP-1
workspace = 2, monitor:eDP-1
workspace = 3, monitor:eDP-1
workspace = 4, monitor:eDP-1
workspace = 5, monitor:eDP-1

# Bind workspaces 6-10 to the external monitor
workspace = 6, monitor:HDMI-A-1
workspace = 7, monitor:HDMI-A-1
workspace = 8, monitor:HDMI-A-1
workspace = 9, monitor:HDMI-A-1
workspace = 10, monitor:HDMI-A-1
