bind r source-file ~/.config/tmux/tmux.conf
# 1. Use Alt + h/l to switch Panes (No prefix needed)
bind -n C-y select-pane -L
bind -n C-u select-pane -R

# 2. Use Alt + t to create a New Window (No prefix needed)
bind -n C-t new-window -c "#{pane_current_path}"

# 3. Use Alt + v for a Vertical Split (No prefix needed)
bind -n C-k split-window -h -c "#{pane_current_path}"

# 4. Solving the Number Problem: Toggle instead of Numbers
# Since numbers are on a layer, just use Alt + [ and Alt + ] to cycle windows
bind -n C-Space next-window

# killing
bind -n C-x kill-pane
bind -n C-q kill-window

# --- Minimalist Floating Status Bar ---

# 1. Background Transparency
set -g status-style "bg=default" 

# 2. Window List (Left Side)
# Format: [1:nvim] [2:term]
set -g window-status-format "#[fg=white,bg=default] #I:#W "
set -g window-status-current-format "#[fg=cyan,bg=default,bold] #I:#W "
set -g status-justify left

# 4. Clean up the left side (remove session name)
set -g status-left ""
# --- Plugins ---
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-battery'

run '~/.config/tmux/plugins/tpm/tpm'
